# Generated by Django 4.0.2 on 2023-06-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('time', models.IntegerField()),
            ],
            options={
                'unique_together': {('day', 'time')},
            },
        ),
    ]
