# Generated by Django 4.0.2 on 2023-06-16 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start', '0002_delete_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=8)),
                ('crd', models.IntegerField()),
                ('cday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.day', to_field='day')),
                ('ctime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.time', to_field='time')),
            ],
            options={
                'unique_together': {('cday', 'ctime', 'cname')},
            },
        ),
    ]
