# Generated by Django 4.0.2 on 2023-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.FloatField(unique=True),
        ),
    ]
