# Generated by Django 4.0.2 on 2023-06-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_alter_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
