# Generated by Django 4.0.2 on 2023-06-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_alter_course_cname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
