# Generated by Django 4.0.2 on 2023-06-16 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_delete_course_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=8, unique=True)),
                ('crd', models.IntegerField()),
                ('cday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.day', to_field='day')),
                ('ctime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.time', to_field='time')),
            ],
            options={
                'unique_together': {('cday', 'ctime', 'cname')},
            },
        ),
    ]
