# Generated by Django 4.0.2 on 2023-06-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_time_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
