# Generated by Django 4.0.2 on 2023-06-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_alter_time_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmane', models.CharField(max_length=30)),
                ('initial', models.CharField(max_length=5, unique=True)),
                ('crd_limit', models.IntegerField()),
            ],
        ),
    ]
