# Generated by Django 4.0.2 on 2023-06-16 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.course', to_field='cname')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.faculty', to_field='initial')),
            ],
            options={
                'unique_together': {('fac', 'cour')},
            },
        ),
    ]
